<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="CustomButton.aspx.vb" Inherits="VCdata.CustomButton" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <telerik:RadStyleSheetManager ID="RadStyleSheetManager1" runat="server">
        </telerik:RadStyleSheetManager>

        <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
            <Scripts>
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.Core.js">
                </asp:ScriptReference>
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQuery.js">
                </asp:ScriptReference>
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQueryInclude.js">
                </asp:ScriptReference>
            </Scripts>
        </telerik:RadScriptManager>
        <telerik:RadCodeBlock ID="RadCodeBlock1" runat="server">
              <script type="text/javascript">

    var popUp;
    function PopUpShowing(sender, eventArgs) {
      popUp = eventArgs.get_popUp();
      var gridWidth = sender.get_element().offsetWidth;
      var gridHeight = sender.get_element().offsetHeight;
      var popUpWidth = popUp.style.width.substr(0, popUp.style.width.indexOf("px"));
      var popUpHeight = popUp.style.height.substr(0, popUp.style.height.indexOf("px"));
      popUp.style.left = ((gridWidth - popUpWidth) / 2 + sender.get_element().offsetLeft).toString() + "px";
      popUp.style.top = ((gridHeight - popUpHeight) / 2 + sender.get_element().offsetTop).toString() + "px";
    }

  </script>
        </telerik:RadCodeBlock>
        <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server">
        </telerik:RadAjaxManager>
        <div>
        </div>
        <telerik:RadGrid ID="RadGrid1" runat="server" OnItemCreated="RadGrid1_ItemCreated" AutoGenerateDeleteColumn="true" AutoGenerateEditColumn="True" RenderMode="Lightweight"  OnItemDataBound ="RadGrid1_ItemDataBound" DataSourceID="SqlDataSource1" Skin="WebBlue"   AllowAutomaticDeletes="True" AllowAutomaticUpdates="True" Height="522px">
<GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>

            <MasterTableView AutoGenerateColumns="False" DataKeyNames="Master_ID" DataSourceID="SqlDataSource1"  EditMode="PopUp" CommandItemDisplay="Top">

                    <EditFormSettings >
 

    </EditFormSettings>
                
                <Columns>
                      <telerik:GridEditCommandColumn UniqueName="EditCommandColumn"  ButtonType="PushButton">
                    </telerik:GridEditCommandColumn>

                    <telerik:GridButtonColumn UniqueName="ViewDetailsColumn"
                        CommandName="Delete" Text="Delete"
                        ButtonType="PushButton">
                    </telerik:GridButtonColumn>
                    <telerik:GridBoundColumn DataField="Master_ID" DataType="System.Int32" FilterControlAltText="Filter Master_ID column" HeaderText="Master_ID" ReadOnly="True" SortExpression="Master_ID" UniqueName="Master_ID">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Firstname" FilterControlAltText="Filter Firstname column" HeaderText="Firstname" SortExpression="Firstname" UniqueName="Firstname">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Lastname" FilterControlAltText="Filter Lastname column" HeaderText="Lastname" SortExpression="Lastname" UniqueName="Lastname">
                    </telerik:GridBoundColumn>
                </Columns>
            </MasterTableView>
              <ClientSettings>
    <ClientEvents OnPopUpShowing="PopUpShowing" />
    <Selecting AllowRowSelect="true" />
                  <Scrolling AllowScroll="True" UseStaticHeaders="True" />
  </ClientSettings>

<FilterMenu RenderMode="Lightweight"></FilterMenu>

<HeaderContextMenu RenderMode="Lightweight"></HeaderContextMenu>
        </telerik:RadGrid>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Chairs] WHERE [Master_ID] = @Master_ID" InsertCommand="INSERT INTO [Chairs] ([Firstname], [Lastname]) VALUES (@Firstname, @Lastname)" SelectCommand="SELECT [Master_ID], [Firstname], [Lastname] FROM [Chairs]" UpdateCommand="UPDATE [Chairs] SET [Firstname] = @Firstname, [Lastname] = @Lastname WHERE [Master_ID] = @Master_ID">
            <DeleteParameters>
                <asp:Parameter Name="Master_ID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Firstname" Type="String" />
                <asp:Parameter Name="Lastname" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Firstname" Type="String" />
                <asp:Parameter Name="Lastname" Type="String" />
                <asp:Parameter Name="Master_ID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
