<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Default.aspx.vb" Inherits="VCdata._Default1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Manage Observations</title>
    <style type="text/css">

body {
    font-family: Arial, Helvetica, sans-serif;
}

</style>
    <style type="text/css">
        .auto-style1 {
            font-size: x-large;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <telerik:RadStyleSheetManager ID="RadStyleSheetManager1" runat="server">
        </telerik:RadStyleSheetManager>
        <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
            <Scripts>
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.Core.js">
                </asp:ScriptReference>
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQuery.js">
                </asp:ScriptReference>
                <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQueryInclude.js">
                </asp:ScriptReference>
            </Scripts>
        </telerik:RadScriptManager>
        <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server">
        </telerik:RadAjaxManager>
        <div>
            <span class="auto-style1"><strong>Manage Observation Requests</strong></span><br />
            <asp:TextBox ID="txtObsDateIn" runat="server"></asp:TextBox>
            <asp:Button ID="btnStartDate" runat="server" Text="Change Filter Date" />
            <br />
            To select MULTIPLE rows, hold down the control key while selecting.<br />
            <telerik:RadGrid ID="RadGrid1" runat="server" DataSourceID="SqlDataSource1"  AllowMultiRowSelection="True"  AllowAutomaticDeletes="True" AllowAutomaticUpdates="True" AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" Skin="WebBlue" AllowSorting="True" >
<GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>
                <ClientSettings>
                    <Selecting AllowRowSelect="True" />
                </ClientSettings>
                <MasterTableView AutoGenerateColumns="False" DataKeyNames="Master_ID" DataSourceID="SqlDataSource1">
                    <Columns>
                        <telerik:GridClientSelectColumn UniqueName="MySelectColumn"   >
                      </telerik:GridClientSelectColumn>
                        <telerik:GridBoundColumn DataField="Master_ID" DataType="System.Int32" FilterControlAltText="Filter Master_ID column" HeaderText="Master_ID" ReadOnly="True" SortExpression="Master_ID" UniqueName="Master_ID">
                        </telerik:GridBoundColumn>
                        <telerik:GridBoundColumn DataField="Course_Name" FilterControlAltText="Filter Course_Name column" HeaderText="Course_Name" SortExpression="Course_Name" UniqueName="Course_Name">
                        </telerik:GridBoundColumn>
                        <telerik:GridBoundColumn DataField="Instructor_Outlook" FilterControlAltText="Filter Instructor_Outlook column" HeaderText="Instructor_Outlook" SortExpression="Instructor_Outlook" UniqueName="Instructor_Outlook">
                        </telerik:GridBoundColumn>
                        <telerik:GridBoundColumn DataField="Chair_Outlook" FilterControlAltText="Filter Chair_Outlook column" HeaderText="Chair_Outlook" SortExpression="Chair_Outlook" UniqueName="Chair_Outlook">
                        </telerik:GridBoundColumn>
                        <telerik:GridBoundColumn DataField="DateIn" DataType="System.DateTime" FilterControlAltText="Filter DateIn column" HeaderText="DateIn" SortExpression="DateIn" UniqueName="DateIn" DataFormatString="{0:MM/dd/yyyy}" >
                        </telerik:GridBoundColumn>

                     <telerik:GridTemplateColumn HeaderText="DateStart" ItemStyle-Width="100px" Visible="true" SortExpression="DateStart" AllowFiltering="false" HeaderStyle-Width="80px" >
                      <ItemTemplate>
                        <asp:Label runat="server" ID="DateStart" Width="80" Text='<%# Eval("DateStart", "{0:MM/dd/yyyy}") %>'>           
                        </asp:Label>
                       </ItemTemplate>

                        <EditItemTemplate>
                           <telerik:RadDatePicker ID="RadDatePicker1" runat="server" SelectedDate='<%# Bind("DateStart")%>'></telerik:RadDatePicker>
                         </EditItemTemplate>

<HeaderStyle Width="80px"></HeaderStyle>

<ItemStyle Width="100px"></ItemStyle>
                       </telerik:GridTemplateColumn>

                     <telerik:GridTemplateColumn HeaderText="DateStop" ItemStyle-Width="100px" Visible="true" SortExpression="DateStop"  AllowFiltering="false">
                      <ItemTemplate>
                        <asp:Label runat="server" ID="DateStop" Text='<%# Eval("DateStop", "{0:MM/dd/yyyy}") %>'>           
                        </asp:Label>
                       </ItemTemplate>

                        <EditItemTemplate>
                           <telerik:RadDatePicker ID="RadDatePicker2" runat="server" SelectedDate='<%# Bind("DateStop")%>'></telerik:RadDatePicker>
                         </EditItemTemplate>

<ItemStyle Width="100px"></ItemStyle>
                       </telerik:GridTemplateColumn>







                        <telerik:GridCheckBoxColumn DataField="IsIn" DataType="System.Boolean" FilterControlAltText="Filter IsIn column" HeaderText="IsIn" SortExpression="IsIn" UniqueName="IsIn">
                        </telerik:GridCheckBoxColumn>
                        <telerik:GridCheckBoxColumn DataField="IsOut" DataType="System.Boolean" FilterControlAltText="Filter IsOut column" HeaderText="IsOut" SortExpression="IsOut" UniqueName="IsOut">
                        </telerik:GridCheckBoxColumn>
                    </Columns>
                </MasterTableView>
            </telerik:RadGrid>
        </div>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [BBObservations] WHERE [Master_ID] = @Master_ID" SelectCommand="SELECT [Master_ID], [Course_Name], [Instructor_Outlook], [Chair_Outlook], [DateIn], [DateStart], [DateStop], [IsIn], [IsOut] FROM [BBObservations] WHERE ([DateIn] &gt; @DateIn)" UpdateCommand="UPDATE [BBObservations] SET [Course_Name] = @Course_Name, [Instructor_Outlook] = @Instructor_Outlook, [Chair_Outlook] = @Chair_Outlook, [DateIn] = @DateIn, [DateStart] = @DateStart, [DateStop] = @DateStop, [IsIn] = @IsIn, [IsOut] = @IsOut WHERE [Master_ID] = @Master_ID" InsertCommand="INSERT INTO [BBObservations] ([Course_Name], [Instructor_Outlook], [Chair_Outlook], [DateIn], [DateStart], [DateStop], [IsIn], [IsOut]) VALUES (@Course_Name, @Instructor_Outlook, @Chair_Outlook, @DateIn, @DateStart, @DateStop, @IsIn, @IsOut)">
            <DeleteParameters>
                <asp:Parameter Name="Master_ID" Type="Int32" />
            </DeleteParameters>

            <InsertParameters>
                <asp:Parameter Name="Course_Name" Type="String" />
                <asp:Parameter Name="Instructor_Outlook" Type="String" />
                <asp:Parameter Name="Chair_Outlook" Type="String" />
                <asp:Parameter Name="DateIn" Type="DateTime" />
                <asp:Parameter Name="DateStart" Type="DateTime" />
                <asp:Parameter Name="DateStop" Type="DateTime" />
                <asp:Parameter Name="IsIn" Type="Boolean" />
                <asp:Parameter Name="IsOut" Type="Boolean" />
            </InsertParameters>

            <SelectParameters>
                <asp:SessionParameter DefaultValue="1/1/2020" Name="DateIn" SessionField="ObsDateIn" Type="DateTime" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="Course_Name" Type="String" />
                <asp:Parameter Name="Instructor_Outlook" Type="String" />
                <asp:Parameter Name="Chair_Outlook" Type="String" />
                <asp:Parameter Name="DateIn" Type="DateTime" />
                <asp:Parameter Name="DateStart" Type="DateTime" />
                <asp:Parameter Name="DateStop" Type="DateTime" />
                <asp:Parameter Name="IsIn" Type="Boolean" />
                <asp:Parameter Name="IsOut" Type="Boolean" />

 
                <asp:Parameter Name="Master_ID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <telerik:RadFormDecorator ID="RadFormDecorator1" Runat="server" DecoratedControls="CheckBoxes" Skin="Material" />
                <br />
                <asp:Button ID="Button1" runat="server" Text="Get Upload Data from selected rows to Enroll Observers" BackColor="#E6FFE6" Font-Bold="True" Width="438px" BorderColor="#009933" />
    &nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button2" runat="server" BackColor="#FFE6E6" Font-Bold="True" Text="Mark selected rows as Removed from BB" Width="415px" BorderColor="Red" />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
        <br />
        <asp:Panel ID="Panel1" runat="server" Visible="False">
            Please copy and paste this data to create a BB user enrollment file<br /> <span class="auto-style2">Go to BB Admin &gt;&gt; Courses &gt;&gt; Enroll Users&nbsp; and use your saved txt or csv file for upload.</span><br /> ______________________________________________________________________<br />
            <br />
            <asp:Literal ID="Literal1" runat="server"></asp:Literal>
            <br />
            <br />
            <asp:Button ID="btnClearInput" runat="server" Text="Clear Text and Refresh Grid" Width="455px" Font-Bold="True" />
        </asp:Panel>
        <br />
        <asp:Panel ID="Panel2" runat="server" Visible="False">
            Please remove these users from their BlackBoard Courses.<br /> <span class="auto-style2">Users must be <span class="auto-style3">MANUALLY removed</span> from each course.</span><br /> ______________________________________________________________________<br />
            <br />
            <asp:Literal ID="Literal2" runat="server"></asp:Literal>
            <br />
            <br />
            <asp:Button ID="btnClearUsers" runat="server" Font-Bold="True" Text="Clear Text and Refresh Grid" Width="461px" />
        </asp:Panel>
        <br />
        <br />
        <br />
        <br />
        <asp:Label ID="lblSQl" runat="server" Visible="False"></asp:Label>
    </form>
</body>
</html>
